### ISSUE TITLE
TYPE "AP_TT_CHAR255" is unknown

### ISSUE THREAD

**Issue by SAPer-Yu1su** [abeljohny/ZAP#1]
When I use ABAPGIT import this repository, Include AP_CLASS File Type AP_TT_CHAR255 Is not defined. How to define this tab type

**Comment by abeljohny** [comment]
Hello, thanks for exploring this project!

Type ZAP_TT_CHAR255 is a table type based on the CHAR255 character string type. You can create a corresponding dictionary table type (via SE11).

Happy coding!

**Comment by SAPer-Yu1su** [comment]
Thank you for your reply, but there are still a few custom types not defined in ZAP_FORMS, namely:

- zap_tt_fields
- zap_tt_dd03l
- zap_ty_fields

**Comment by abeljohny** [comment]
You’re right! Thanks for catching that. Here’s how to define these types in the dictionary (based on the source, as I don’t have system access to verify):
- ZAP_TY_FIELDS: Single-column structure with the column name FIELDNAME of type String
- ZAP_TT_FIELDS: Table type based on ZAP_TY_FIELDS
- ZAP_TT_DD03L: Table type based on DD03L

Let me know if you need further help!

**Comment by SAPer-Yu1su** [comment]
Thanks a lot，there are no errors with these three types, finally found that ZAP_NULL is unknown. Why not use INITIAL directly?

**Comment by abeljohny** [comment]
`zap_null`'s part of the DSL syntax (mentioned in the project’s **Usage** section). The whole point of the `zap_` prefix was to make DSL-specific stuff easy to spot — also useful for things like text editor extensions. You can define it like this: `DATA: zap_null TYPE REF TO data VALUE IS INITIAL.`. Thanks!

**Comment by SAPer-Yu1su** [comment]
OK, Thank you for your detailed answer, the test code can run completely,  wish you happy everyday! Let's ABAP greater~
